### ISSUE TITLE
class instantiation with overrides

### ISSUE THREAD

**Issue by rcirka** [eed3si9n/treehugger#32]
I am trying to instantiation a class with definition overrides, however the code isn't generating correctly, it is adding an equals sign.

Lets say I have a class definition: 

class Foo() {
  val bar: String = ""
}

In normal scala code, I can do this to override the definition:

val f = new Foo() {
  override val bar = "blah"
}

I am trying to mimic this in treehugger.

VAL("f") := NEW("Foo") := BLOCK(
  VAL("bar") := LIT("blah")
)

However, it is generating the following code (note the equals sign after Foo): 

val f = new Foo() = {
  override val bar() = "blah"
}

Is there a way to get this generated correctly?

**Comment by eed3si9n** [comment]
See http://eed3si9n.com/treehugger/new.html#Anonymous+classes

**Comment by rcirka** [comment]
I thought about that, but the ANONDEF method doesn't except parameters. For example, if I want to do the following:

class Foo(str: String) {
 val bar: String = ""
 }

val f = new Foo("test)  {
 override val bar() = "blah"
 }

I can't do
NEW(ANONDEF("Foo", LIT("test") : BLOCK := ...

**Comment by eed3si9n** [comment]
I see then it's probably currently a missing feature then.

**Comment by rcirka** [comment]
After fooling around with it, I was able to get it to work.

NEW(ANONDEF(REF("Foo").APPLY(LIT("blah")) : BLOCK(
  ...
))

Much thanks for all your hard work, treehugger has been extremely useful.
