### ISSUE TITLE
Publish artifact for scala 2.12

### ISSUE THREAD

**Issue by thyming** [eed3si9n/treehugger#40]

**Comment by ennru** [comment]
@eed3si9n Did you publish the artifacts somewhere? I can't see them at [Sonatype](https://oss.sonatype.org/content/repositories/releases/com/eed3si9n/).

**Comment by eed3si9n** [comment]
I guess it got closed when I merged, but never published?

**Comment by evan-ck** [comment]
👍

**Comment by evan-ck** [comment]
@eed3si9n Please publish this.

**Comment by eed3si9n** [comment]
I just published 0.4.2 - https://oss.sonatype.org/content/repositories/public/com/eed3si9n/treehugger_2.12/0.4.2/

I might follow up with 0.4.3 rolling back a PR that I no longer agree.
