### ISSUE TITLE
Unable to create a class definition with an empty value parameter list

### ISSUE THREAD

**Issue by JBakouny** [eed3si9n/treehugger#44]
Hi,

I was unable to generate the following code:
```
  sealed abstract class Tree[A]
  case class Leaf[A]() extends Tree[A]
  case class Node[A](info: A, left: Tree[A], right: Tree[A]) extends Tree[A]
```
Notably, the definition of the class Leaf is generated without the parenthesis:
```
case class Leaf[A] extends Tree[A]
```
While I had expected the generation of the following code:
```
case class Leaf[A]() extends Tree[A]
```
The tree used to define the case class is given below:
```
        val caseDef: Tree =
          CASECLASSDEF(name)
            .withTypeParams(parentTypeDefs)
            .withParams(Nil)
            .withParents(createTypeWithGenericParams(parentName, parentTypeDefs))
            .tree
```

It seems to me that the parenthesis should always be printed for case class definitions, even when the parameter list is empty.

Any help with this issue would be much appreciated.

Best regards,

Joseph.

**Comment by jniq** [comment]
I believe I'm running into the same issue, but on methods which have empty parameter lists. This looks like the culprit: https://github.com/eed3si9n/treehugger/blob/master/library/src/main/scala/treehugger/treehuggerdsls.scala#L361

**Comment by JBakouny** [comment]
Hi James,

Thank you for your response.

I do not have enough information to know if the issue you encountered has the same root cause as the one described above.

It seems to me that the culprit for this issue described above is the printer. In fact, the printer does not take into consideration the fact that Scala requires the use of parenthesis for all case class definitions, even those with an empty parameter list.

Hence, the below class definition is accepted by the Scala compiler since class definitions are not required to have parenthesis:
```
class A //legal
```
But the below case class definition is not accepted by the Scala compiler since case class definitions are required to have parenthesis:
```
case class A // illegal
```
The printer should therefore synthesize the below Scala code for case class definitions:
```
case class A() // legal
```

In this context, a fix for this issue has already been proposed under pull request https://github.com/eed3si9n/treehugger/pull/45

Best regards,

Joseph.

**Comment by JBakouny** [comment]
@eed3si9n Any news regarding this issue and the fix proposed by pull request #45 ?

Thank you.

**Comment by eed3si9n** [comment]
I guess this slipped through the crack. Merged now.

**Comment by JBakouny** [comment]
Thanks :)
