### ISSUE TITLE
test failure (DSL_1BasicDeclSpec) on 2.11.12

### ISSUE THREAD

**Issue by SethTisue** [eed3si9n/treehugger#59]
this turned up in the Scala community build: https://scala-ci.typesafe.com/view/scala-2.11.x/job/scala-2.11.x-jdk11-integrate-community-build/281/artifact/logs/treehugger-build.log

```
[treehugger] [error] Failed: Total 189, Failed 1, Errors 0, Passed 188
[treehugger] [error] Failed tests:
[treehugger] [error] 	DSL_1BasicDeclSpec
```

it's reproducible outside of dbuild with just `++2.11.12` followed by `test`

weirdly, `testOnly *DSL_1BasicDeclSpec` succeeds

**Comment by eed3si9n** [comment]
on https://github.com/eed3si9n/treehugger/commit/5fb93efdc0203d04d88ba16b1748b224e5bf1648 (current latest, also used by Community Builds), I am able to run ++2.11.12 test fine locally both JDK 8 and JDK 11. also it ran ok 12 days ago on Travis CI - https://travis-ci.org/eed3si9n/treehugger/jobs/583445064

The failure log says

```
[treehugger] [info]   Import clauses are written as
[treehugger] [error]     x `IMPORT(sym)` or `IMPORT("scala.collection.mutable")`.
[treehugger] [error]  import scala.mutable doesn't equal import scala.collection.mutable (DSL_1BasicDeclSpec.scala:223)
```

Not sure what could cause that.

**Comment by SethTisue** [comment]
here's a full log of this happening locally on my own machine, outside dbuild: https://gist.github.com/SethTisue5117fb4d89a5eb135fb5b9d392ec1fcb

**Comment by SethTisue** [comment]
I'm not able to reproduce this currently

maybe #65 somehow randomly fixed it? 🤷
